namespace Duplicati.Proprietary.Office365.SourceItems;

/// <summary>
/// The type of the source items found in Office365
/// </summary>
public enum SourceItemType
{
    MetaRoot,
    MetaRootUsers,
    MetaRootGroups,
    MetaRootSites,
    Calendar,
    CalendarGroup,
    CalendarEvent,
    CalendarEventContent,
    CalendarEventAttachment,
    Chat,
    ChatHostedContent,
    ChatMessage,
    ChatMember,
    Drive,
    DriveFile,
    DriveFolder,
    Group,
    GroupCalendar,
    GroupCalendarEvent,
    GroupMailbox,
    GroupFiles,
    GroupPlanner,
    GroupTeams,
    GroupNotes,
    GroupChannel,
    GroupChannelMessage,
    GroupChannelMessageReply,
    GroupChannelTab,
    GroupInstalledApp,
    GroupMember,
    GroupOwner,
    GroupSettings,
    GroupConversation,
    GroupConversationThread,
    GroupConversationThreadPost,
    Notebook,
    NotebookSection,
    NotebookSectionGroup,
    Planner,
    Site,
    SharePointList,
    SharePointListItem,
    SharePointListItemAttachment,
    TaskList,
    TaskListTask,
    TaskListLinkedResource,
    TaskListChecklistItem,
    UserMailbox,
    UserMailboxFolder,
    UserMailboxEmail,
    UserMailboxSettings,
    UserMailboxRule,
    User,
    UserContact,
    UserContactPhoto,
    UserContactGroup,
    UserContactFolder,
    UserProfile,
    UserCalendar,
    UserContacts,
    UserTasks,
    UserNotes,
    UserChats,

    UserPlannerTasks,
    PlannerBucket
}