// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Duplicati.Server.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Program {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Program() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Duplicati.Server.Strings.Program", typeof(Program).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WebserverWebrootDescription {
            get {
                return ResourceManager.GetString("WebserverWebrootDescription", resourceCulture);
            }
        }
        
        internal static string WebserverPortDescription {
            get {
                return ResourceManager.GetString("WebserverPortDescription", resourceCulture);
            }
        }
        
        internal static string HelpCommandDescription {
            get {
                return ResourceManager.GetString("HelpCommandDescription", resourceCulture);
            }
        }
        
        internal static string AnotherInstanceDetected {
            get {
                return ResourceManager.GetString("AnotherInstanceDetected", resourceCulture);
            }
        }
        
        internal static string DatabaseOpenError {
            get {
                return ResourceManager.GetString("DatabaseOpenError", resourceCulture);
            }
        }
        
        internal static string ShowstausCommandDescription {
            get {
                return ResourceManager.GetString("ShowstausCommandDescription", resourceCulture);
            }
        }
        
        internal static string WebserverPasswordDescription {
            get {
                return ResourceManager.GetString("WebserverPasswordDescription", resourceCulture);
            }
        }
        
        internal static string LanguageSelectionError {
            get {
                return ResourceManager.GetString("LanguageSelectionError", resourceCulture);
            }
        }
        
        internal static string LogfileCommandDescription {
            get {
                return ResourceManager.GetString("LogfileCommandDescription", resourceCulture);
            }
        }
        
        internal static string WebserverInterfaceDescription {
            get {
                return ResourceManager.GetString("WebserverInterfaceDescription", resourceCulture);
            }
        }
        
        internal static string WrongSQLiteVersion {
            get {
                return ResourceManager.GetString("WrongSQLiteVersion", resourceCulture);
            }
        }
        
        internal static string UnencrypteddatabaseCommandDescription {
            get {
                return ResourceManager.GetString("UnencrypteddatabaseCommandDescription", resourceCulture);
            }
        }
        
        internal static string PortablemodeCommandDescription {
            get {
                return ResourceManager.GetString("PortablemodeCommandDescription", resourceCulture);
            }
        }
        
        internal static string HelpDisplayDialog {
            get {
                return ResourceManager.GetString("HelpDisplayDialog", resourceCulture);
            }
        }
        
        internal static string SeriousError {
            get {
                return ResourceManager.GetString("SeriousError", resourceCulture);
            }
        }
        
        internal static string LoglevelCommandDescription {
            get {
                return ResourceManager.GetString("LoglevelCommandDescription", resourceCulture);
            }
        }
        
        internal static string HelpDisplayFormat {
            get {
                return ResourceManager.GetString("HelpDisplayFormat", resourceCulture);
            }
        }
        
        internal static string StartupFailure {
            get {
                return ResourceManager.GetString("StartupFailure", resourceCulture);
            }
        }
    }
}
