// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Duplicati.CommandLine.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Program {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Program() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Duplicati.CommandLine.Strings.Program", typeof(Program).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IncludeShort {
            get {
                return ResourceManager.GetString("IncludeShort", resourceCulture);
            }
        }
        
        internal static string WrongNumberOfCommandsError_v2 {
            get {
                return ResourceManager.GetString("WrongNumberOfCommandsError_v2", resourceCulture);
            }
        }
        
        internal static string SupportedEncryptionModulesHeader {
            get {
                return ResourceManager.GetString("SupportedEncryptionModulesHeader", resourceCulture);
            }
        }
        
        internal static string TimeParseError {
            get {
                return ResourceManager.GetString("TimeParseError", resourceCulture);
            }
        }
        
        internal static string GenericModulesHeader {
            get {
                return ResourceManager.GetString("GenericModulesHeader", resourceCulture);
            }
        }
        
        internal static string QuietConsoleOptionShort {
            get {
                return ResourceManager.GetString("QuietConsoleOptionShort", resourceCulture);
            }
        }
        
        internal static string ControlFilesOptionLong {
            get {
                return ResourceManager.GetString("ControlFilesOptionLong", resourceCulture);
            }
        }
        
        internal static string ExcludeShort {
            get {
                return ResourceManager.GetString("ExcludeShort", resourceCulture);
            }
        }
        
        internal static string WouldDeleteBackups {
            get {
                return ResourceManager.GetString("WouldDeleteBackups", resourceCulture);
            }
        }
        
        internal static string IncludeLong {
            get {
                return ResourceManager.GetString("IncludeLong", resourceCulture);
            }
        }
        
        internal static string DeletedBackups {
            get {
                return ResourceManager.GetString("DeletedBackups", resourceCulture);
            }
        }
        
        internal static string SupportedOptionsHeader {
            get {
                return ResourceManager.GetString("SupportedOptionsHeader", resourceCulture);
            }
        }
        
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        internal static string DeleteCommandNeedsOptions {
            get {
                return ResourceManager.GetString("DeleteCommandNeedsOptions", resourceCulture);
            }
        }
        
        internal static string InternalOptionUsedError {
            get {
                return ResourceManager.GetString("InternalOptionUsedError", resourceCulture);
            }
        }
        
        internal static string UnhandledInnerException {
            get {
                return ResourceManager.GetString("UnhandledInnerException", resourceCulture);
            }
        }
        
        internal static string NoFilesetsMatching {
            get {
                return ResourceManager.GetString("NoFilesetsMatching", resourceCulture);
            }
        }
        
        internal static string FiltersCannotBeUsedWithFileError {
            get {
                return ResourceManager.GetString("FiltersCannotBeUsedWithFileError", resourceCulture);
            }
        }
        
        internal static string QuietConsoleOptionLong {
            get {
                return ResourceManager.GetString("QuietConsoleOptionLong", resourceCulture);
            }
        }
        
        internal static string SupportedCompressionModulesHeader {
            get {
                return ResourceManager.GetString("SupportedCompressionModulesHeader", resourceCulture);
            }
        }
        
        internal static string ModuleIsLoadedAutomatically {
            get {
                return ResourceManager.GetString("ModuleIsLoadedAutomatically", resourceCulture);
            }
        }
        
        internal static string ParametersFileOptionLong {
            get {
                return ResourceManager.GetString("ParametersFileOptionLong", resourceCulture);
            }
        }
        
        internal static string IntegerParseError {
            get {
                return ResourceManager.GetString("IntegerParseError", resourceCulture);
            }
        }
        
        internal static string ModuleIsNotLoadedAutomatically {
            get {
                return ResourceManager.GetString("ModuleIsNotLoadedAutomatically", resourceCulture);
            }
        }
        
        internal static string ParametersFileOptionShort {
            get {
                return ResourceManager.GetString("ParametersFileOptionShort", resourceCulture);
            }
        }
        
        internal static string InvalidCommandError {
            get {
                return ResourceManager.GetString("InvalidCommandError", resourceCulture);
            }
        }
        
        internal static string ExcludeLong {
            get {
                return ResourceManager.GetString("ExcludeLong", resourceCulture);
            }
        }
        
        internal static string FailedToParseParametersFileError {
            get {
                return ResourceManager.GetString("FailedToParseParametersFileError", resourceCulture);
            }
        }
        
        internal static string SupportedBackendsHeader {
            get {
                return ResourceManager.GetString("SupportedBackendsHeader", resourceCulture);
            }
        }
        
        internal static string ControlFilesOptionShort {
            get {
                return ResourceManager.GetString("ControlFilesOptionShort", resourceCulture);
            }
        }
    }
}
