svn checkout -r 50 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r50
svn checkout -r 100 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r100
svn checkout -r 150 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r150
svn checkout -r 200 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r200
svn checkout -r 250 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r250
svn checkout -r 251 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r251
svn checkout -r 252 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r252
svn checkout -r 253 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r253
svn checkout -r 254 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r254
svn checkout -r 255 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r255
svn checkout -r 256 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r256
svn checkout -r 257 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r257
svn checkout -r 258 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r258
svn checkout -r 259 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r259
svn checkout -r 260 http://dsmcbe.googlecode.com/svn/trunk/ bin/Debug/DSMCBE/r260