//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Wizard_pages.Add_backup.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FinishedAdd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinishedAdd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Wizard_pages.Add_backup.Strings.FinishedAdd", typeof(FinishedAdd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have now entered all the required data, and can now create the backup..
        /// </summary>
        internal static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup modifications are now ready to be saved..
        /// </summary>
        internal static string PageDescriptionModify {
            get {
                return ResourceManager.GetString("PageDescriptionModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to add backup.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to save changes.
        /// </summary>
        internal static string PageTitleModify {
            get {
                return ResourceManager.GetString("PageTitleModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string SummaryAction {
            get {
                return ResourceManager.GetString("SummaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new backup.
        /// </summary>
        internal static string SummaryActionAdd {
            get {
                return ResourceManager.GetString("SummaryActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify backup.
        /// </summary>
        internal static string SummaryActionModify {
            get {
                return ResourceManager.GetString("SummaryActionModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string SummaryDestination {
            get {
                return ResourceManager.GetString("SummaryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path.
        /// </summary>
        internal static string SummaryDestinationPath {
            get {
                return ResourceManager.GetString("SummaryDestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full backup each.
        /// </summary>
        internal static string SummaryFullBackupEach {
            get {
                return ResourceManager.GetString("SummaryFullBackupEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep full backups.
        /// </summary>
        internal static string SummaryKeepFullBackups {
            get {
                return ResourceManager.GetString("SummaryKeepFullBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string SummaryRepeat {
            get {
                return ResourceManager.GetString("SummaryRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder.
        /// </summary>
        internal static string SummarySourceFolder {
            get {
                return ResourceManager.GetString("SummarySourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        internal static string SummaryWhen {
            get {
                return ResourceManager.GetString("SummaryWhen", resourceCulture);
            }
        }
    }
}
