//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Wizard_pages.Add_backup.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasswordSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Wizard_pages.Add_backup.Strings.PasswordSettings", typeof(PasswordSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the current password to a new random one?.
        /// </summary>
        internal static string ChangePasswordQuestion {
            get {
                return ResourceManager.GetString("ChangePasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password, remove the check mark next to the box to disable encryption of the backups..
        /// </summary>
        internal static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup is protected with password.
        /// </summary>
        internal static string EnablePasswordRestoreText {
            get {
                return ResourceManager.GetString("EnablePasswordRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the encryption modules: {0}.
        /// </summary>
        internal static string EncryptionModuleLoadError {
            get {
                return ResourceManager.GetString("EncryptionModuleLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have generated a new random password.
        ///Please write down the password and store it in a safe location.
        ///Without this password, you will not be able to recover a single file from the backups!
        ///
        ///You cannot recover the password from within Duplicati after saving this setup.
        ///
        ///Are you sure you have a safely stored copy of the generated password?.
        /// </summary>
        internal static string NewGeneratedPasswordWarning {
            get {
                return ResourceManager.GetString("NewGeneratedPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an encryption method..
        /// </summary>
        internal static string NoEncryptionMethodSelected {
            get {
                return ResourceManager.GetString("NoEncryptionMethodSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the backup is stored on machine or device that is not under your direct control,
        ///it is possible that others may view the files you have stored in the backups.
        ///It is highly recomended that you enable encryption.
        ///Do you want to continue without encryption?.
        /// </summary>
        internal static string NoPasswordWarning {
            get {
                return ResourceManager.GetString("NoPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page you can select options that protect your backups from being read or altered..
        /// </summary>
        internal static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the encryption settings that were used to create the backup originally.
        /// </summary>
        internal static string PageDescriptionRestore {
            get {
                return ResourceManager.GetString("PageDescriptionRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select password for the backup.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ****************** WARNING ***********************
        ///You are modifying the password settings for an existing backup.
        ///If you save these changes, you will no longer be able to recover previously backed up files.
        ///Are you absolutely sure you want to continue?.
        /// </summary>
        internal static string PasswordChangedWarning {
            get {
                return ResourceManager.GetString("PasswordChangedWarning", resourceCulture);
            }
        }
    }
}
