//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Wizard_pages.Add_backup.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SelectWhen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectWhen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Wizard_pages.Add_backup.Strings.SelectWhen", typeof(SelectWhen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no repetition set, so the backup will never run.\nThis is fine if you only want to run the backup manually, but it is not recomended.\nDo you want to continue?.
        /// </summary>
        internal static string NoRepetitionWarning {
            get {
                return ResourceManager.GetString("NoRepetitionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page you may set up when the backup is run. Automatically repeating the backup ensure that you have a backup, without requiring any action from you..
        /// </summary>
        internal static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select when the backup should run.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time you entered is in the past..
        /// </summary>
        internal static string TimeIsInThePastWarning {
            get {
                return ResourceManager.GetString("TimeIsInThePastWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time you entered will occur shortly..
        /// </summary>
        internal static string TimeOccursShortlyWarning {
            get {
                return ResourceManager.GetString("TimeOccursShortlyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration entered is less than five minutes. That is not acceptable..
        /// </summary>
        internal static string TooShortDurationError {
            get {
                return ResourceManager.GetString("TooShortDurationError", resourceCulture);
            }
        }
    }
}
