//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationSetup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationSetup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Strings.ApplicationSetup", typeof(ApplicationSetup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During backup, errors, warnings.
        /// </summary>
        internal static string BalloonNotification_Continous {
            get {
                return ResourceManager.GetString("BalloonNotification_Continous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string BalloonNotification_Errors {
            get {
                return ResourceManager.GetString("BalloonNotification_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications.
        /// </summary>
        internal static string BalloonNotification_Off {
            get {
                return ResourceManager.GetString("BalloonNotification_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start, errors, warnings.
        /// </summary>
        internal static string BalloonNotification_Start {
            get {
                return ResourceManager.GetString("BalloonNotification_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start, stop, errors, warnings.
        /// </summary>
        internal static string BalloonNotification_StartAndStop {
            get {
                return ResourceManager.GetString("BalloonNotification_StartAndStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors, warnings.
        /// </summary>
        internal static string BalloonNotification_Warnings {
            get {
                return ResourceManager.GetString("BalloonNotification_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache size: {0}.
        /// </summary>
        internal static string CacheSize {
            get {
                return ResourceManager.GetString("CacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating cache size ....
        /// </summary>
        internal static string CalculatingCacheSize {
            get {
                return ResourceManager.GetString("CalculatingCacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete signature files in the folder: 
        ///{0}.
        /// </summary>
        internal static string ConfirmCacheDelete {
            get {
                return ResourceManager.GetString("ConfirmCacheDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System language, {0}.
        /// </summary>
        internal static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati Options, version {0}.
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading encryption modules: {0}.
        /// </summary>
        internal static string EncryptionModuleLoadError {
            get {
                return ResourceManager.GetString("EncryptionModuleLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while examining the folder: {0}.
        ///Do you want to use that folder anyway?.
        /// </summary>
        internal static string ErrorWhileExaminingFolder {
            get {
                return ResourceManager.GetString("ErrorWhileExaminingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder selected does not contain the file: {0}.
        ///Do you want to use that folder anyway?.
        /// </summary>
        internal static string FolderIsMissingFile {
            get {
                return ResourceManager.GetString("FolderIsMissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language has changed. This will take effect after you restart Duplicati..
        /// </summary>
        internal static string LanguageChangedWarning {
            get {
                return ResourceManager.GetString("LanguageChangedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving settings: {0}.
        /// </summary>
        internal static string SaveExtensionError {
            get {
                return ResourceManager.GetString("SaveExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading setting controls: {0}.
        /// </summary>
        internal static string SettingControlsLoadError {
            get {
                return ResourceManager.GetString("SettingControlsLoadError", resourceCulture);
            }
        }
    }
}
