//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        internal static string FifteenMinutes {
            get {
                return ResourceManager.GetString("FifteenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes.
        /// </summary>
        internal static string FiveMinutes {
            get {
                return ResourceManager.GetString("FiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured: {0}.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full backup duration entered is not valid: {0}.
        /// </summary>
        internal static string InvalidDuration {
            get {
                return ResourceManager.GetString("InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string MenuPause {
            get {
                return ResourceManager.GetString("MenuPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string MenuResume {
            get {
                return ResourceManager.GetString("MenuResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoMinutes {
            get {
                return ResourceManager.GetString("NoMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One day.
        /// </summary>
        internal static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        internal static string OneMinute {
            get {
                return ResourceManager.GetString("OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month.
        /// </summary>
        internal static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One week.
        /// </summary>
        internal static string OneWeek {
            get {
                return ResourceManager.GetString("OneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string SixtyMinutes {
            get {
                return ResourceManager.GetString("SixtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string ThirtyMinutes {
            get {
                return ResourceManager.GetString("ThirtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above normal.
        /// </summary>
        internal static string ThreadPriorityAboveNormal {
            get {
                return ResourceManager.GetString("ThreadPriorityAboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below normal.
        /// </summary>
        internal static string ThreadPriorityBelowNormal {
            get {
                return ResourceManager.GetString("ThreadPriorityBelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest.
        /// </summary>
        internal static string ThreadPriorityHighest {
            get {
                return ResourceManager.GetString("ThreadPriorityHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ThreadPriorityNormal {
            get {
                return ResourceManager.GetString("ThreadPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest.
        /// </summary>
        internal static string ThreadPriortyLowest {
            get {
                return ResourceManager.GetString("ThreadPriortyLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three months.
        /// </summary>
        internal static string ThreeMonths {
            get {
                return ResourceManager.GetString("ThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two weeks.
        /// </summary>
        internal static string TwoWeeks {
            get {
                return ResourceManager.GetString("TwoWeeks", resourceCulture);
            }
        }
    }
}
