//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListBackupFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListBackupFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Strings.ListBackupFiles", typeof(ListBackupFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data returned.
        /// </summary>
        internal static string NoDataError {
            get {
                return ResourceManager.GetString("NoDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added file.
        /// </summary>
        internal static string TooltipAddedFile {
            get {
                return ResourceManager.GetString("TooltipAddedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added folder.
        /// </summary>
        internal static string TooltipAddedFolder {
            get {
                return ResourceManager.GetString("TooltipAddedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added or modified file.
        /// </summary>
        internal static string TooltipAddedOrModifiedFile {
            get {
                return ResourceManager.GetString("TooltipAddedOrModifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control file.
        /// </summary>
        internal static string TooltipControlFile {
            get {
                return ResourceManager.GetString("TooltipControlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted file.
        /// </summary>
        internal static string TooltipDeletedFile {
            get {
                return ResourceManager.GetString("TooltipDeletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted folder.
        /// </summary>
        internal static string TooltipDeletedFolder {
            get {
                return ResourceManager.GetString("TooltipDeletedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing folder.
        /// </summary>
        internal static string TooltipExistingFolder {
            get {
                return ResourceManager.GetString("TooltipExistingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete file.
        /// </summary>
        internal static string TooltipIncompleteFile {
            get {
                return ResourceManager.GetString("TooltipIncompleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified file.
        /// </summary>
        internal static string TooltipModifiedFile {
            get {
                return ResourceManager.GetString("TooltipModifiedFile", resourceCulture);
            }
        }
    }
}
