//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Strings.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run backup {0}: {1}.
        /// </summary>
        internal static string BalloonTip_Error {
            get {
                return ResourceManager.GetString("BalloonTip_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string BalloonTip_Running {
            get {
                return ResourceManager.GetString("BalloonTip_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {0}.
        /// </summary>
        internal static string BalloonTip_Started {
            get {
                return ResourceManager.GetString("BalloonTip_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished {0}.
        /// </summary>
        internal static string BalloonTip_Stopped {
            get {
                return ResourceManager.GetString("BalloonTip_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup {0} gave a warning.
        /// </summary>
        internal static string BalloonTip_Warning {
            get {
                return ResourceManager.GetString("BalloonTip_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backup is currently running, do you want to stop the backup so Duplicati can exit?.
        /// </summary>
        internal static string ExitWhileBackupIsRunningQuestion {
            get {
                return ResourceManager.GetString("ExitWhileBackupIsRunningQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup named &quot;{0}&quot; was found {1} times.
        /// </summary>
        internal static string MultipleNamedBackupsFound {
            get {
                return ResourceManager.GetString("MultipleNamedBackupsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup group named &quot;{0}&quot; was not found.
        /// </summary>
        internal static string NamedBackupGroupNotFound {
            get {
                return ResourceManager.GetString("NamedBackupGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup named &quot;{0}&quot; was not found.
        /// </summary>
        internal static string NamedBackupNotFound {
            get {
                return ResourceManager.GetString("NamedBackupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute the Pause request: {0}.
        /// </summary>
        internal static string PauseOperationFailed {
            get {
                return ResourceManager.GetString("PauseOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati is attempting to quit, but a backup is running.
        ///Do you want Duplicati to continue waiting for the backup to stop?.
        /// </summary>
        internal static string TerminateForExitQuestion {
            get {
                return ResourceManager.GetString("TerminateForExitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati is currently paused.
        /// </summary>
        internal static string TrayStatusPause {
            get {
                return ResourceManager.GetString("TrayStatusPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati is ready.
        /// </summary>
        internal static string TrayStatusReady {
            get {
                return ResourceManager.GetString("TrayStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati is running {0}.
        /// </summary>
        internal static string TrayStatusRunning {
            get {
                return ResourceManager.GetString("TrayStatusRunning", resourceCulture);
            }
        }
    }
}
