//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Strings.ServiceStatus", typeof(ServiceStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string BackupImmediate {
            get {
                return ResourceManager.GetString("BackupImmediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed backup.
        /// </summary>
        internal static string BackupStatusError {
            get {
                return ResourceManager.GetString("BackupStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull backup.
        /// </summary>
        internal static string BackupStatusOK {
            get {
                return ResourceManager.GetString("BackupStatusOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup only processed some of the files.
        /// </summary>
        internal static string BackupStatusPartial {
            get {
                return ResourceManager.GetString("BackupStatusPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed backup with warnings.
        /// </summary>
        internal static string BackupStatusWarning {
            get {
                return ResourceManager.GetString("BackupStatusWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati {0} - Status.
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup has no changes.
        /// </summary>
        internal static string NoFilesInBackupMessages {
            get {
                return ResourceManager.GetString("NoFilesInBackupMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Duplicati.
        /// </summary>
        internal static string QuickActionExit {
            get {
                return ResourceManager.GetString("QuickActionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string QuickActionPause {
            get {
                return ResourceManager.GetString("QuickActionPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause for 10 minutes.
        /// </summary>
        internal static string QuickActionPause10 {
            get {
                return ResourceManager.GetString("QuickActionPause10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause for 15 minutes.
        /// </summary>
        internal static string QuickActionPause15 {
            get {
                return ResourceManager.GetString("QuickActionPause15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause for 30 minutes.
        /// </summary>
        internal static string QuickActionPause30 {
            get {
                return ResourceManager.GetString("QuickActionPause30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause for 5 minutes.
        /// </summary>
        internal static string QuickActionPause5 {
            get {
                return ResourceManager.GetString("QuickActionPause5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause for 60 minutes.
        /// </summary>
        internal static string QuickActionPause60 {
            get {
                return ResourceManager.GetString("QuickActionPause60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string QuickActionResume {
            get {
                return ResourceManager.GetString("QuickActionResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the current backup.
        /// </summary>
        internal static string QuickActionStop {
            get {
                return ResourceManager.GetString("QuickActionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle options ....
        /// </summary>
        internal static string QuickActionThrottle {
            get {
                return ResourceManager.GetString("QuickActionThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select action -.
        /// </summary>
        internal static string SelectQuickAction {
            get {
                return ResourceManager.GetString("SelectQuickAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup: {0}.
        /// </summary>
        internal static string StatusBackup {
            get {
                return ResourceManager.GetString("StatusBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati is currently paused.
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: {0}.
        /// </summary>
        internal static string StatusRestore {
            get {
                return ResourceManager.GetString("StatusRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for next backup.
        /// </summary>
        internal static string StatusWaiting {
            get {
                return ResourceManager.GetString("StatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced &gt;&gt;&gt;.
        /// </summary>
        internal static string SwitchToAdvanced {
            get {
                return ResourceManager.GetString("SwitchToAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple &lt;&lt;&lt;.
        /// </summary>
        internal static string SwitchToSimple {
            get {
                return ResourceManager.GetString("SwitchToSimple", resourceCulture);
            }
        }
    }
}
