//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Strings.TaskType", typeof(TaskType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full backup.
        /// </summary>
        internal static string FullBackup {
            get {
                return ResourceManager.GetString("FullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental backup.
        /// </summary>
        internal static string IncrementalBackup {
            get {
                return ResourceManager.GetString("IncrementalBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List actual files.
        /// </summary>
        internal static string ListActualFiles {
            get {
                return ResourceManager.GetString("ListActualFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List backup entries.
        /// </summary>
        internal static string ListBackupEntries {
            get {
                return ResourceManager.GetString("ListBackupEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List backups.
        /// </summary>
        internal static string ListBackups {
            get {
                return ResourceManager.GetString("ListBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List files.
        /// </summary>
        internal static string ListFiles {
            get {
                return ResourceManager.GetString("ListFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all but n full.
        /// </summary>
        internal static string RemoveAllButNFull {
            get {
                return ResourceManager.GetString("RemoveAllButNFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove older than.
        /// </summary>
        internal static string RemoveOlderThan {
            get {
                return ResourceManager.GetString("RemoveOlderThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore setup.
        /// </summary>
        internal static string RestoreSetup {
            get {
                return ResourceManager.GetString("RestoreSetup", resourceCulture);
            }
        }
    }
}
