//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WizardHandler {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WizardHandler() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Strings.WizardHandler", typeof(WizardHandler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati is currently paused, so the backup won&apos;t run until Duplicati is resumed.
        ///Do you want Duplicati to resume now so the backup can run immediately?.
        /// </summary>
        internal static string ResumeNowQuestion {
            get {
                return ResourceManager.GetString("ResumeNowQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous Duplicati setup is now restored!.
        /// </summary>
        internal static string SetupRestoreSuccess {
            get {
                return ResourceManager.GetString("SetupRestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while attempting to stop the running backup: {0}.
        /// </summary>
        internal static string StopBackupError {
            get {
                return ResourceManager.GetString("StopBackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup you want to delete is currently running.
        ///Do you want to stop it so the delete can proceed?.
        /// </summary>
        internal static string StopRunningBackupQuestion {
            get {
                return ResourceManager.GetString("StopRunningBackupQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati attempted to stop the backup, but did not succeed.
        ///Press &quot;Finish&quot; to attempt the delete again..
        /// </summary>
        internal static string UnableToStopBackupError {
            get {
                return ResourceManager.GetString("UnableToStopBackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicati Setup Wizard.
        /// </summary>
        internal static string WizardFormTitle {
            get {
                return ResourceManager.GetString("WizardFormTitle", resourceCulture);
            }
        }
    }
}
