// Copyright (c) 2026 Duplicati Inc. All rights reserved.

namespace Duplicati.Proprietary.GoogleWorkspace.SourceItems;

public enum SourceItemType
{
    MetaRoot,
    MetaRootUsers,
    MetaRootGroups,
    MetaRootSharedDrives,
    MetaRootSites,
    MetaRootOrganizationalUnits,
    User,
    UserGmail,
    UserDrive,
    UserCalendar,
    UserContacts,
    UserTasks,
    GmailLabel,
    GmailMessage,
    GmailAttachment,
    GmailSettings,
    Drive,
    DriveFile,
    DriveFolder,
    DrivePermission,
    DriveFileContent,
    DriveFileMetadata,
    DriveFileComment,
    DriveFileRevision,
    SharedDrives,
    Calendar,
    CalendarEvent,
    CalendarEventAttachment,
    Contact,
    ContactGroup,
    ContactPhoto,
    TaskList,
    Task,
    UserKeep,
    UserChat,
    KeepNote,
    KeepNoteAttachment,
    UserProfile,
    OrganizationalUnit,
    Group,
    GroupMember,
    GroupSettings,
    GroupAliases,
    GroupConversations,
    Site,
    ChatSpaceType,
    ChatSpace,
    ChatMessage,
    ChatAttachment
}
