//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duplicati.GUI.Wizard_pages.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SelectBackup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectBackup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duplicati.GUI.Wizard_pages.Strings.SelectBackup", typeof(SelectBackup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a backup before you can continue.
        /// </summary>
        internal static string NoActionSelected {
            get {
                return ResourceManager.GetString("NoActionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the list below, select the backup you want to modify.
        /// </summary>
        internal static string PageHelptextEdit {
            get {
                return ResourceManager.GetString("PageHelptextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the list below, select the backup you want to delete.
        /// </summary>
        internal static string PageHelptextRemove {
            get {
                return ResourceManager.GetString("PageHelptextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the list below, select the backup you want to restore.
        /// </summary>
        internal static string PageHelptextRestore {
            get {
                return ResourceManager.GetString("PageHelptextRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the list below, select the backup you want to run immediately.
        /// </summary>
        internal static string PageHelptextRunNow {
            get {
                return ResourceManager.GetString("PageHelptextRunNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown action.
        /// </summary>
        internal static string PageHelptextUnknown {
            get {
                return ResourceManager.GetString("PageHelptextUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the backup to modify.
        /// </summary>
        internal static string PageTitleEdit {
            get {
                return ResourceManager.GetString("PageTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the backup to remove.
        /// </summary>
        internal static string PageTitleRemove {
            get {
                return ResourceManager.GetString("PageTitleRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the backup to restore.
        /// </summary>
        internal static string PageTitleRestore {
            get {
                return ResourceManager.GetString("PageTitleRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the backup to run now.
        /// </summary>
        internal static string PageTitleRunNow {
            get {
                return ResourceManager.GetString("PageTitleRunNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown action.
        /// </summary>
        internal static string PageTitleUnknown {
            get {
                return ResourceManager.GetString("PageTitleUnknown", resourceCulture);
            }
        }
    }
}
